### ISSUE TITLE
Feature request: warning message when two or more flags are active on the map

### ISSUE THREAD

**Issue by TadhgEomonn** [altairwei/Stoneshard-AutoPathfinder#1]
When two or more flags are on the map, AutoPathfinder will happily send you to one of them (the older one?!). More often than not (Murphy's Law), it is sending you in the wrong direction. 

A quality of life feature would be a friendly *warning* that AutoPathfinder may be sending you to an undesired location when there are multiple targets on the map. This warning should also include a suggestion that you remove all but one of them. This would resolve the ambiguity and ensure that you are hiking to your desired target location.

**Comment by altairwei** [comment]
As I have mentioned in Nexus Mod, the AutoPathfinder will move you to the nearest location if multiple markers exist on the map. 

You make a good suggestion though. I'm going to make this an optional feature (go to the nearest location), and the default doesn't move the player but sends a warning when multiple markers exist.

**Comment by altairwei** [comment]
Done
