### ISSUE TITLE
A couple suggestions and a bug

### ISSUE THREAD

**Issue by TadhgEomonn** [altairwei/Stoneshard-AutoPathfinder#2]
1. Grammer fix: When multiple map markers are present on the map, the warning should read:
PlayerCharacterName _does not_ | _doesn't_ know where to go.

2. Suggestion: In settings, the map-mark label should read: _map marker_ or better yet _destination map marker_ next to the choose box.

3. Bug: If **not** using the closest map marker option is chosen (settings box unchecked), then the program should only target the selected destination map markers, not all map markers of any kind. Example: I have two different map markers on the map--one as a reminder of some local danger, the other as my AutoPathfinder marker--the program gives me a warning about two or more markers and does not proceed to my selected designation. This is a bug. The program should only look for designated map markers before proceeding and disregard the other map marker types on the map.

**Comment by altairwei** [comment]
Thanks for the report. I think I've fixed your third point, which I updated on 8 October on the Nexus page. Could you take a look and let me know if you still see it?

**Comment by TadhgEomonn** [comment]
AutoPathfinder works as one would expect. 

This mod is a major QoL improvement to the game: kudos. Thanks for the quick fix, too.

**Comment by altairwei** [comment]
Thank you for your feedback. Also, regarding your localization text suggestion, I will adopt the ‘Map Marker’ instead of the 'Destination Map Marker', which is too long to be displayed in the setting screen (the position of the ComboBox is fixed and cannot be changed).

**Comment by altairwei** [comment]
Done
